# Generated by Django 4.0.3 on 2022-03-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hood',
            name='image',
            field=models.ImageField(default='../images/neighbour.jpg', upload_to='hood'),
        ),
    ]
