# Generated by Django 4.0.3 on 2022-03-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0002_alter_post_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
